# Site settings
title: Gaurav Gupta blog
email: gv22ga@gmail.com
description: "In search for AGI"
baseurl: ""
url: "http://gv22ga.github.io"
github_username:  gv22ga

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
